url = "put URL OF VRA"
deployment_name = "PUT DEPLOYMENT NAME"
project_name = "PUT PROJECT NAME"
catalog_item_name = "PUT CATALOG NAME"
catalog_item_version = "VERSION"
zid = "put YOUR ID TO LOGIN"

application_id           = "VAULES"
business_unit            = "VAULES"
ci                       = "VAULES"
cost_code                = "VAULES"
environment              = "VAULES"
service_owner            = "VAULES"
sub_environment          = "VAULES"
support_group            = "VAULES"
region                   = "eu-west-1"
role                     = "VAULES"